Repository Party-Time-Job/Party-Time-Job, pull requests merged in 2024-03, with the labels that each got.

#30 [공통 컴포넌트] 알림 모달 공통 컴포넌트 생성
  public/close.svg
  src/app/globals.css
  src/shared/NotificationModal/NotificationItem.tsx
  src/shared/NotificationModal/NotificationModal.tsx
  src/shared/NotificationModal/type.ts
  src/shared/NotificationModal/utils/calcDiff.ts
Labels: 세팅, 일반회원 페이지

#33 공고 리스트 페이지 ui 구현
  next.config.mjs
  package-lock.json
  package.json
  public/data/mock.json
  src/app/notice/page.tsx
  src/entities/Post.tsx
  src/utils/formatDateTime.ts
  src/utils/formatHourlyPay.ts
  src/widgets/AllNotice.tsx
  src/widgets/CustomNotice.tsx
  tailwind.config.ts
  types.d.ts
Labels: 공고 페이지

#37 [공통 컴포넌트] 버튼 및 페이지 타이틀 공통 컴포넌트 생성 및 FSD 폴더 구조 추가
  src/app/globals.css
  src/feature/Button/ButtonClick.tsx
  src/pages/.gitkeep
  src/shared/Button/Button.tsx
  src/shared/Button/type.ts
  src/shared/Title/Title.tsx
  src/shared/Title/type.ts
Labels: 세팅, 일반회원 페이지

#44 인풋 공동 컴포넌트 리액트 훅 폼 연동 작업
  src/app/login/page.tsx
  src/shared/ui/Input.tsx
Labels: 세팅

#53 공고 리스트 정렬 기능
  src/entities/Notice/NoticeDetail.tsx
  src/entities/Notice/NoticeList.tsx
  src/entities/Notice/NoticeListHeader.tsx
  src/entities/Notice/SortButtonList.tsx
  src/features/Sort/SortButton.tsx
  src/features/Sort/SortSelect.tsx
  src/features/Sort/utils/sortNotice.ts
  src/widgets/api/updateInformation.ts
Labels: 공고 페이지

#57 [공통 컴포넌트] 추가 기능을 위한 토스트 및 다이얼로그 공통 컴포넌트 구현
  public/check.svg
  public/confirm.svg
  src/app/globals.css
  src/shared/ui/Dialog/Dialog.tsx
  src/shared/ui/Dialog/type.ts
  src/shared/ui/Dialog/ui/CheckDialogUi.tsx
  src/shared/ui/Dialog/ui/ConfirmDialogUi.tsx
  src/shared/ui/Dialog/ui/DialogContainer.tsx
  src/shared/ui/Toast/Toast.tsx
  src/shared/ui/Toast/ui/ShowToast.tsx
  src/shared/ui/Toast/ui/ToastUi.tsx
  src/widgets/api/updateInformation.ts
Labels: 세팅, 일반회원 페이지

#58 가게 등록 폼 ui 제작 및 임시 기능 구현
  public/camera.svg
  src/app/store/details/page.tsx
  src/app/store/details/registration/recruitment/[id]/page.tsx
  src/app/store/details/registration/store-info/[id]/page.tsx
  src/app/store/editor/.gitkeep
  src/app/store/register/.gitkeep
  src/entities/Employer/MyStore.tsx
  src/entities/Employer/RegisteredRecruitment.tsx
  src/entities/Employer/UI/EmpolyerEmptyData.tsx
  src/features/Create-Store/CreateStore.tsx
  src/features/Filter/Filter.tsx
  src/pages/EmployerPage/DetailsPage.tsx
  src/pages/EmployerPage/RegistRecruitmentPage.tsx
  src/pages/EmployerPage/RegistStorePage.tsx
  src/shared/constants/Address.ts
  src/shared/constants/Classification.ts
  src/shared/ui/Select/type.ts
  src/shared/ui/Text.tsx
  src/widgets/api/updateInformation.ts
Labels: 사장님 페이지

#61 공고 상세 필터 기능 구현
  public/close-white.svg
  src/app/globals.css
  src/app/notice/page.tsx
  src/entities/Notice/CustomNotice.tsx
  src/entities/Notice/NoticeDetail.tsx
  src/entities/Notice/NoticeList.tsx
  src/entities/Notice/NoticeListHeader.tsx
  src/entities/Notice/SortButtonList.tsx
  src/entities/Notice/types.ts
  src/entities/Post/DetailPost.tsx
  src/entities/Post/Post.tsx
  src/entities/Post/types.ts
  src/features/Filter/Filter.tsx
  src/features/Filter/UI/FilterUi.tsx
  src/features/Filter/UI/SelectedAddress.tsx
  src/features/Filter/utils/filterNotice.ts
  src/features/Sort/SortButton.tsx
  src/features/Sort/utils/sortNotice.ts
  src/pages/NoticeDetailPage/NoticeDetailPage.tsx
  src/pages/NoticePage/NoticePage.tsx
  src/shared/ui/Input.tsx
Labels: 공고 페이지

#70 최근 본 공고 기능, 공고 검색 기능 구현
  next.config.mjs
  src/app/search/page.tsx
  src/entities/Notice/NoticeDetail.tsx
  src/entities/Notice/NoticeList.tsx
  src/entities/Notice/utils/getSavedNotice.ts
  src/entities/Notice/utils/saveSeenNotice.ts
  src/entities/Post/DetailPost.tsx
  src/entities/Post/types.ts
  src/pages/NoticeDetailPage/NoticeDetailPage.tsx
  src/pages/NoticePage/NoticePage.tsx
  src/pages/searchPage/SearchPage.tsx
  src/pages/searchPage/getSearchList.ts
  src/shared/api/RequestMethod.ts
  src/widgets/Footer/ui/FooterIcon.tsx
  src/widgets/Header/ui/HeaderInput.tsx
Labels: 공고 페이지

#73 공고 지원, 취소 기능, 각 상황 모달 구현
  public/modal-alert.svg
  public/modal-check.svg
  src/entities/Notice/NoticeDetail.tsx
  src/entities/Notice/utils/saveSeenNotice.ts
  src/entities/Post/DetailPost.tsx
  src/entities/Post/types.ts
  src/features/Modal/Modal.tsx
  src/pages/NoticeDetailPage/NoticeDetailPage.tsx
  src/pages/NoticeDetailPage/utils/getUserToken.ts
  src/shared/ui/Logo.tsx
Labels: 공고 페이지

#80 [일반회원 페이지] 프로필 상세 페이지 스타일 수정 및 수정사항 파악
  next.config.mjs
  src/shared/NotificationModal/NotificationItem.tsx
  src/shared/NotificationModal/NotificationModal.tsx
  src/shared/api/RequestMethod.ts
  src/shared/ui/Loader.tsx
  src/shared/ui/Pagination/ui/PaginationUi.tsx
  src/shared/ui/Table/ui/TableBodyUi.tsx
  src/shared/ui/Table/ui/TableContainerUi.tsx
  src/shared/ui/Table/ui/TableHeadUi.tsx
  src/shared/ui/Title.tsx
  src/widgets/Application/ui/ApplicationDataUi.tsx
  src/widgets/Application/ui/NoRegisterUi.tsx
  src/widgets/NoProfile/NoProfile.tsx
  src/widgets/NoProfile/NoProfileRegister.tsx
  src/widgets/ProfileContainer/ui/ProfileContainerUi.tsx
  src/widgets/RegisterModal/RegisterModal.tsx
Labels: 일반회원 페이지

#81 [가게 등록 페이지]가게 정보 편집 기능 구현
  src/app/store/details/[id]/page.tsx
  src/app/store/details/page.tsx
  src/app/store/details/registration/recruitment/[id]/page.tsx
  src/app/store/details/registration/store-info/[id]/page.tsx
  src/app/store/register/.gitkeep
  src/app/store/registration/recruitment/[id]/page.tsx
  src/app/store/registration/store-info/[id]/page.tsx
  src/entities/Employer/EmptyRecruitment.tsx
  src/entities/Employer/EmptyStore.tsx
  src/entities/Employer/MyStore.tsx
  src/entities/Employer/RegisteredRecruitment.tsx
  src/entities/Employer/UI/EmpolyerEmptyData.tsx
  src/features/Create-Recruitment/CreateRecruitment.tsx
  src/features/Create-Store/CreateStore.tsx
  src/features/Create-Store/StoreImage.tsx
  src/features/Create-Store/Type.ts
  src/pages/EmployerPage/Api/type.ts
  src/pages/EmployerPage/DetailsPage.tsx
  src/pages/EmployerPage/RegistRecruitmentPage.tsx
  src/pages/EmployerPage/RegistStorePage.tsx
  src/widgets/Footer/ui/FooterIcon.tsx
Labels: 사장님 페이지

#83 [일반회원 페이지] 페이지네이션 이동 기능 구현 및 드롭다운 옵션 선택 기능 구현
  src/shared/hooks/useSelect.tsx
  src/shared/ui/Pagination/ui/ArrowUi.tsx
  src/shared/ui/Pagination/ui/PaginationUi.tsx
  src/shared/ui/Select/Select.tsx
  src/shared/ui/Select/ui/SelectUi.tsx
  src/shared/ui/Table/ui/TableBodyUi.tsx
  src/widgets/ProfileContainer/ui/ProfileContainerUi.tsx
  src/widgets/RegisterModal/RegisterModal.tsx
Labels: 일반회원 페이지

#92 공고 목록 페이지 페이지네이션, 공고 정렬, 필터 기능 api-쿼리스트링 적용
  next.config.mjs
  src/entities/Notice/NoticeDetail.tsx
  src/entities/Notice/NoticeList.tsx
  src/entities/Notice/NoticeListHeader.tsx
  src/entities/Notice/Pagination.tsx
  src/entities/Notice/SortButtonList.tsx
  src/entities/Notice/utils/getNoticeList.ts
  src/entities/Notice/utils/saveSeenNotice.ts
  src/entities/Notice/utils/setPagination.ts
  src/features/Filter/UI/FilterUi.tsx
  src/features/Filter/utils/filterNotice.ts
  src/features/Sort/SortButton.tsx
  src/features/Sort/SortSelect.tsx
  src/features/Sort/utils/convertDate.ts
  src/features/Sort/utils/convertSortText.ts
  src/pages/NoticeDetailPage/NoticeDetailPage.tsx
  src/pages/NoticePage/NoticePage.tsx
  src/pages/searchPage/SearchPage.tsx
Labels: 공고 페이지

#94 [일반회원 페이지] 간단한 수정
  src/app/layout.tsx
  src/app/profile/page.tsx
  src/shared/ui/Pagination/Pagination.tsx
  src/shared/ui/Table/Table.tsx
  src/widgets/ProfileContainer/ui/ProfileContainerUi.tsx
Labels: 일반회원 페이지

#95 지난 공고 UI, 커스텀 훅 분리, filter 지난 날짜 선택 방지
  public/disable-clock-icon.svg
  public/disable-location-icon.svg
  src/entities/Notice/NoticeDetail.tsx
  src/entities/Notice/NoticeList.tsx
  src/entities/Notice/hooks/useApplication.ts
  src/entities/Notice/hooks/useDetailNotice.ts
  src/entities/Notice/hooks/useOutDatedNotice.ts
  src/entities/Post/DetailPost.tsx
  src/entities/Post/Post.tsx
  src/entities/Post/utils/formatDateTime.ts
  src/features/Filter/UI/FilterUi.tsx
  src/shared/ui/ClosedNoticeImage.tsx
Labels: 공고 페이지

#97 [일반회원 페이지] 필요없는 주석 제거 및 eslint 주석 추가
  src/app/profile/error.tsx
  src/features/CreatePortal.tsx
  src/shared/NotificationModal/NotificationItem.tsx
  src/shared/api/RequestMethod.ts
  src/shared/api/axiosInstanceType.ts
  src/shared/utils/calcDiff.ts
  src/shared/utils/calculateTime.ts
  src/widgets/api/getApplication.ts
  src/widgets/api/getInformation.ts
  src/widgets/api/updateInformation.ts
Labels: 일반회원 페이지

#98 [일반회원 페이지] 프로필 페이지 테이블 내 일자 수정
  src/shared/utils/formatTime.ts
Labels: 일반회원 페이지

#101 마감된 공고 UI 처리, 맞춤 공고 주소 기준으로, 각 컴포넌트 커스텀 훅 분리
  public/data/mock.json
  src/entities/Notice/CustomNotice.tsx
  src/entities/Notice/NoticeCategory.tsx
  src/entities/Notice/NoticeDetail.tsx
  src/entities/Notice/NoticeList.tsx
  src/entities/Notice/NoticeListHeader.tsx
  src/entities/Notice/SortButtonList.tsx
  src/entities/Notice/hooks/useApplication.ts
  src/entities/Notice/hooks/useCustomNotice.ts
  src/entities/Notice/hooks/useDetailNotice.ts
  src/entities/Notice/hooks/useNoticeListHeader.ts
  src/entities/Notice/hooks/useNoticeListState.ts
  src/entities/Notice/hooks/useNoticeStatus.ts
  src/entities/Notice/utils/getNoticeList.ts
  src/entities/Post/DetailPost.tsx
  src/entities/Post/Post.tsx
  src/entities/Post/hooks/useDetailPost.ts
  src/features/Filter/UI/FilterUi.tsx
  src/features/Filter/hooks/useFilter.ts
  src/features/Sort/SortButton.tsx
  src/pages/NoticeDetailPage/NoticeDetailPage.tsx
  src/pages/NoticeDetailPage/hooks/useNoticeDetail.ts
  src/pages/NoticePage/NoticePage.tsx
Labels: 공고 페이지

#102 추천 공고, 공고 리스트 페이지, 공고 상세 페이지, 사장님 공고 상세 페이지 스켈레톤 UI 적용
  src/entities/Employer/EmployerNoticeDetail.tsx
  src/entities/Notice/CustomNotice.tsx
  src/entities/Notice/CustomNoticeLoading.tsx
  src/entities/Notice/NoticeDescription.tsx
  src/entities/Notice/NoticeDetail.tsx
  src/entities/Notice/NoticeList.tsx
  src/entities/Notice/NoticeListLoading.tsx
  src/entities/Post/DetailPostLoading.tsx
Labels: 공고 페이지

#105 [employer page] 가게 정보 등록 로직 수정
  next.config.mjs
  src/app/store/details/[id]/page.tsx
  src/app/store/registration/store-info/[id]/page.tsx
  src/entities/Employer/EmployerNoticeList.tsx
  src/entities/Employer/EmployerPost.tsx
  src/entities/Employer/MyStore.tsx
  src/features/Create-Recruitment/CreateRecruitment.tsx
  src/features/Create-Store/CreateStore.tsx
  src/features/Create-Store/Type.ts
  src/pages/EmployerPage/DetailsPage.tsx
  src/pages/EmployerPage/RegistStorePage.tsx
  src/widgets/Header/ui/MyStoreLink.tsx
Labels: 사장님 페이지

#107 [EmployerPage] 모집 공고 등록 기능 구현
  src/app/store/details/[id]/page.tsx
  src/entities/Employer/EmployerNoticeList.tsx
  src/entities/Employer/EmployerPost.tsx
  src/entities/Notice/NoticeList.tsx
  src/features/Create-Recruitment/CreateRecruitment.tsx
  src/pages/EmployerPage/DetailsPage.tsx
Labels: 사장님 페이지

#109 [일반회원 페이지] revalidation 선언 및 연락처 자동 하이픈 추가
  src/app/profile/page.tsx
  src/widgets/Application/Application.tsx
  src/widgets/RegisterModal/RegisterModal.tsx
Labels: 일반회원 페이지

#111 Post, DetailPost UI 수정, 맞춤 공고에 마감, 지난 공고 제외
  src/entities/Notice/CustomNoticeLoading.tsx
  src/entities/Notice/NoticeList.tsx
  src/entities/Notice/NoticeListLoading.tsx
  src/entities/Notice/hooks/useCustomNotice.ts
  src/entities/Post/DetailPost.tsx
  src/entities/Post/DetailPostLoading.tsx
  src/entities/Post/Post.tsx
Labels: 공고 페이지

#122 [세팅] README.md 파일 1차 작성
  README.md
  public/readme-1.png
Labels: 세팅

#124 [세팅] README.md 파일 dev 브랜치에 추가
  README.md
  public/readme-1.png
Labels: 세팅

#126 [EmployerPage] 공고 편집 기능 구현
  src/app/shop/details/page.tsx
  src/app/shop/details/type.ts
  src/app/shop/notice-detail/[shopId]/[noticeId]/page.tsx
  src/app/shop/registration/recruitment/[id]/page.tsx
  src/app/shop/registration/recruitment/[id]/type.ts
  src/app/shop/registration/shop-info/[shopId]/page.tsx
  src/app/store/editor/.gitkeep
  src/app/store/registration/recruitment/[id]/page.tsx
  src/entities/Employer/EmployerNoticeDetail.tsx
  src/entities/Employer/EmployerNoticeList.tsx
  src/entities/Employer/EmptyShop.tsx
  src/entities/Employer/MyShop.tsx
  src/entities/Post/EmployerDetailPost.tsx
  src/features/Create-Recruitment/CreateRecruitment.tsx
  src/features/Create-Shop/CreateShop.tsx
  src/features/Create-Shop/Type.ts
  src/features/Create-Store/StoreImage.tsx
  src/page/EmployerPage/DetailsPage.tsx
  src/page/EmployerPage/RegistRecruitmentPage.tsx
  src/page/EmployerPage/RegistShopPage.tsx
  src/page/EmployerPage/RegistStorePage.tsx
  src/page/EmployerPage/type.ts
  src/widgets/Header/ui/MyStoreLink.tsx
Labels: 사장님 페이지

#127 [Fix] Employer - shop - details 페이지 버그 수정
  src/app/shop/details/page.tsx
  src/app/shop/registration/shop-info/[shopId]/page.tsx
  src/features/Create-Shop/CreateShop.tsx
  src/page/EmployerPage/DetailsPage.tsx
Labels: 사장님 페이지

#134 맞춤 공고 자동 스크롤, 필터 주소 선택 4개이상 막기, 최근 본 공고 없을 때 UI
  src/entities/Notice/CustomNotice.tsx
  src/entities/Notice/NoticeCategory.tsx
  src/entities/Notice/NoticeListLoading.tsx
  src/entities/Notice/Pagination.tsx
  src/entities/Notice/hooks/useCustomNoticeScroll.ts
  src/features/Filter/UI/FilterUi.tsx
Labels: 공고 페이지

#144 [세팅] 로딩 상태 변경
  src/app/detail/[shopId]/[noticeId]/layout.tsx
  src/app/notice/layout.tsx
  src/entities/Employer/EmployerNoticeDetail.tsx
  src/entities/Notice/CustomNotice.tsx
  src/entities/Notice/NoticeDetail.tsx
  src/entities/Notice/NoticeList.tsx
  src/shared/ui/Loader.tsx
Labels: 세팅

#145 [세팅] 로딩 상태 수정
  src/entities/Employer/Api/.gitkeep
  src/entities/Notice/NoticeList.tsx
  src/entities/Notice/NoticeListLoading.tsx
  src/page/Recruitment/[id]/.gitkeep
  src/page/UserPage/.gitkeep
Labels: 세팅

#147 Style: 로딩 스타일 변경
  src/shared/ui/Loader.tsx
Labels: 세팅

#149 [EmployerPage] 가게 정보 이미지 관련
  src/entities/Employer/MyShop.tsx
  src/features/Create-Recruitment/CreateRecruitment.tsx
  src/features/Create-Shop/CreateShop.tsx
  src/features/Create-Shop/removeQuery.ts
Labels: 사장님 페이지

#152 [EmployerPage] 이미지 등록 오류 수정
  src/features/Create-Shop/CreateShop.tsx
  src/page/EmployerPage/DetailsPage.tsx
Labels: 사장님 페이지

#160 로그인, 회원가입 페이지 로고 이동 링크 수정
  src/features/AccountPageLogoLink/AccountPageLogoLink.tsx
Labels: 로그인/회원가입 페이지

#162 [세팅] 로딩 상태 수정
  src/app/landing/layout.tsx
  src/app/landing/page.tsx
  src/app/page.tsx
  src/app/profile/page.tsx
  src/app/signup/layout.tsx
  src/shared/ui/Loader.tsx
  src/widgets/Header/ui/LogoutButton.tsx
Labels: 세팅

#164 가게 등록 페이지 이미지 추가하기 인풋 숨기기
  src/features/Create-Shop/CreateShop.tsx
Labels: 사장님 페이지

#166 맞춤 공고 갯수 수정
  src/entities/Notice/hooks/useCustomNotice.ts
  src/entities/Notice/hooks/useCustomNoticeScroll.ts
Labels: 공고 페이지

#168 파비콘 적용
  src/app/layout.tsx
Labels: 세팅

#169 [세팅] 새로고침 시 로딩 상태 구현 수정
  src/shared/ui/Loader.tsx
Labels: 세팅

#170 [EployerPage] 이미지 업로드 수정
  src/features/Create-Shop/CreateShop.tsx
Labels: 사장님 페이지

#173 스타일 개선
  src/entities/Notice/CustomNotice.tsx
  src/entities/Post/Post.tsx
Labels: 공고 페이지

#178 readme 수정
  README.md
  public/readme-1 2.png
  public/readme-1.png
  public/readme-2.png
  public/readme-3.png
  public/readme-4.png
  public/readme-5.png
Labels: 세팅
